{{cookiecutter.environment}}: 
  dummy: dummy
{% if cookiecutter.with_ssl != "False" %}
  ssl:
    # This is the name of the certificate to reference in the elb section.
    {{cookiecutter.project_name}}_{{cookiecutter.environment}}-cert:
      # This should live in the encrypted secrets file, but the cert and chain are fine here.
      key: |
        {{ cookiecutter.ssl_key }}
{% endif %}