{{cookiecutter.environment}}: 
  dummy: dummy
{% if cookiecutter.with_ssl != "False" %}
  ssl:
    # This is the name of the certificate to reference in the elb section.
    my-cert:
      cert: |
        -----BEGIN CERTIFICATE-----
        blahblahblah
        -----END CERTIFICATE-----
      # This should live in the encrypted secrets file, but the cert and chain are fine here.
      key: |
        -----BEGIN RSA PRIVATE KEY-----
        blahblahblah
        -----END RSA PRIVATE KEY-----
{% endif %}